### ISSUE TITLE
RunDNC looking for Data Viz, beta testers, and design & feature testers

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/projects#27]
From @WoobieTuesday 

Hey all! The #run-dnc project sprung from #debug-politics and has really hit the ground running! They've built a platform to gather a popular vote and do outreach for the DNC Chair election the last week in February. Current needs are: *data viz person(s)*, *beta testers*, front end *design & feature* suggestions (minor because you'll see it's already really beautiful!) as well as *UX*!

The program is populated with dummy data thus far but it's very near completion. If you're interested in helping them achieve 2/1 launch date, please join the discussion in #run-dnc! See @mikebloomberg2 with project questions and @kamilla with engineering questions! Thanks!

**Comment by rapi-progcode** [comment]
@WoobieTuesday what's the status of this?
